<a href="https://colab.research.google.com/github/kim-spirit/aipython/blob/main/240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#시험 문제 1
a = list(map(int,input().split())) # 두 개의 변수를 받는 법
if sum(a) > 100 :
  if a[0] > 40 and a[1] > 40 :
    print('PASS')
  elif a[0] < 40 :
    print('ENG FAIL')
  else :
    print('MATH FAIL')
else :
  print('FAIL')

69 35
MATH FAIL


In [3]:
#시험 문제 2
# n개의 숫자가 공백없이 입력, 이 숫자를 모두 합쳐서 합을 추력하는 프로그램을 작성하시오.
Num = input()
NUM_List = list(Num)
aa = map(int,NUM_List)

print(sum(aa))

700001
8


In [4]:
# 시험 문제 3
# 다음 리스트에서 확장자가 png나 jpg인 파일명.확장자를 출력하는 파이썬 코드를 작성하세요
n = int(input())
a=[input() for _ in range(n)]
b = [i for i in a if i.split('.')[-1] == 'jpg' or i.split('.')[-1] == 'png']
print(b)

2


KeyboardInterrupt: Interrupted by user

In [7]:
import numpy as np
arr=np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


In [8]:
import numpy as np
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
import numpy as np
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [22]:
A = np.array([[ 1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
A.shape
print(A[3,3])
print(A[: 2, :2])
print(A[3:, 3:])
print(A[0:2, : ])
print(A[:, -2 : ])



19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [21]:
# 36까지의 숫자 생성
A = np.arange(1, 37)

# 4열로 나누기
matrix = A.reshape(-1, 4)
print(matrix)

re_A = A.reshape(3,4,3)
A_F = A.flatten()

print(re_A)
print(A_F)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [13]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[0])
print(arr1[0,2])
print(arr1[1:])
print(arr1[arr1 > 5])

[1 2 3]
3
[[4 5 6]
 [7 8 9]]
[6 7 8 9]
